### PR TITLE
Add temporal_degrain

### PR DESCRIPTION
**Pull request by adworacz**
It offers several improvements over previous versions, which I've detailed in the class "changelog".

There's still room for improvements, including additional parity with the Avisynth version, potentially switching to DFTTest instead of fft3dfilter by default, and a few other bits and bobs.

Also, more documentation is required for each parameter, but that can come over time.

Lastly, I noticed that mvtools.Compensate was broken (took me a bit to debug). It was selecting the wrong clip from the cycle (off by one error).

### CODE REVIEW

**Comment by Setsugennoao** [comment]
Heyo! Can you split this into three PRs?

1. Add TemporalDegrain2
2. Add normalize_thsad
3. Fix MVTools.compensate

**Comment by adworacz** [comment]
Sure thing!

**Comment by adworacz** [comment]
Okay, I've added PRs for normalize_thscd and MVTools.compensate. I'll rebase this branch off of them once they're merged upstream.

**Comment by Setsugennoao** [comment]
All right, i think i finished rewriting and refactoring the code to the vs-* standards.
You can check out if i typo'd something, and we can rewrite docstrings from [this](https://github.com/Irrational-Encoding-Wizardry/vs-denoise/pull/90/commits/57b9c0604ad753b7f7b475ff056d06e09df91fe0) commit etc.
We can also add as many limiters we want, in `TemporalLimit` and post-processors in `PostProcess`

**Comment by adworacz** [comment]
Wow, looks like you pretty much rewrote the entire thing.

I'll give the changes a proper review soon. I see a few changes that might require some tweaks, but I'll set aside some time to do a proper deep dive. One thing we might want to do is make DFTTest the default limiter instead of FFT3D, since there's such a difference in speed and quality. But I'll see what else I notice as I go.

Did you notice any quality changes with your refactors? I'd figure there shouldn't be any, but wasn't sure if there were some tradeoffs made.

**Comment by Setsugennoao** [comment]
If I didn't typo anything, it should be the same.

**Pull request merged**
